import ipaddress
import random
from collections import defaultdict
from decimal import Decimal
from pathlib import Path

import yaml
from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand, CommandError

from dcim.models import (
    Device,
    DeviceRole,
    DeviceType,
    Interface,
    Location,
    Manufacturer,
    Platform,
    Rack,
    Region,
    Site,
)
from extras.models import CustomField
from ipam.models import IPAddress, Prefix, Service, VLAN, VRF
from virtualization.models import Cluster, ClusterGroup, ClusterType, VirtualMachine, VMInterface


SYN_MARK = "SYN:"


def apportion(total, items, weight_key="weight"):
    """Largest-remainder apportionment. Returns {key/index: integer_count}."""
    if total <= 0:
        return {i: 0 for i in range(len(items))}
    weights = [float(item[weight_key]) for item in items]
    weight_sum = sum(weights)
    if weight_sum <= 0:
        raise ValueError("Sum of weights must be > 0")
    raw = [total * w / weight_sum for w in weights]
    base = [int(x) for x in raw]
    remainder = total - sum(base)
    order = sorted(range(len(items)), key=lambda i: raw[i] - base[i], reverse=True)
    for i in order[:remainder]:
        base[i] += 1
    return {i: base[i] for i in range(len(items))}


def make_weighted_plan(total, items, weight_key="weight"):
    """Build an exact-size plan honoring configured weights."""
    counts = apportion(total, items, weight_key=weight_key)
    plan = []
    for idx, item in enumerate(items):
        plan.extend([item] * counts[idx])
    return plan


def case_data(profile, asset_class, software_name=None):
    """Structured synthetic software/fault ground truth stored as custom fields."""
    return {
        "syn_asset_class": asset_class,
        "syn_software_name": software_name or profile.get("name", ""),
        "syn_software_version": str(profile.get("version", "")),
        "syn_case": profile.get("case", "normal"),
        "syn_eol": bool(profile.get("eol", False)),
        "syn_known_vulnerable": bool(profile.get("known_vulnerable", False)),
        "syn_vulnerability_ids": list(profile.get("vulnerability_ids", [])),
        "syn_failure_mode": profile.get("failure_mode", "none"),
    }


def scaled(value, scale, minimum=0):
    if value <= 0:
        return 0
    return max(minimum, int(round(value * scale)))


def host_addresses(cidr, count, start_offset=1):
    """
    Yield `count` IPv4 hosts as /32 strings without materializing the network.
    Safe for large pools.
    """
    network = ipaddress.ip_network(cidr)
    if network.version != 4:
        raise ValueError(f"Only IPv4 is implemented in this generator: {cidr}")
    first = int(network.network_address) + start_offset
    last = int(network.broadcast_address) - 1
    if first + count - 1 > last:
        raise ValueError(f"Pool {cidr} has insufficient usable addresses for {count} rows")
    for value in range(first, first + count):
        yield f"{ipaddress.ip_address(value)}/32"


class Command(BaseCommand):
    help = "Generate a deterministic, large synthetic Viettel-like datacenter dataset for NetBox 3.1.7"

    def add_arguments(self, parser):
        parser.add_argument("--config", required=True, help="Path to viettel_demo.yaml")
        parser.add_argument(
            "--scale",
            type=float,
            default=1.0,
            help="Multiply all large target counts. Use 0.001 for smoke test; 1.0 for full dataset.",
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete rows generated by this command before creating new data. Use only on a test DB.",
        )
        parser.add_argument(
            "--validate-only",
            action="store_true",
            help="Do not generate; only show current synthetic counts.",
        )
        parser.add_argument(
            "--no-ip-pool",
            action="store_true",
            help="Create only IPs assigned to generated Device/VM interfaces, not the remaining large pool.",
        )

    def handle(self, *args, **options):
        config_path = Path(options["config"])
        if not config_path.exists():
            raise CommandError(f"Config not found: {config_path}")
        with config_path.open("r", encoding="utf-8") as f:
            self.cfg = yaml.safe_load(f)

        self.scale = options["scale"]
        if self.scale <= 0:
            raise CommandError("--scale must be > 0")

        self.rng = random.Random(int(self.cfg.get("seed", 20260826)))
        self.targets = self._scaled_targets()

        if options["reset"]:
            self._reset()

        if options["validate_only"]:
            self._print_counts()
            self._print_hard_case_summary()
            return

        self._assert_clean()
        self.stdout.write(self.style.WARNING(f"Generating synthetic dataset at scale={self.scale}"))
        self.stdout.write(str(self.targets))

        self._create_geography()
        self._create_reference_data()
        self._ensure_custom_fields()
        self._create_racks()
        self._create_vrfs_vlans_prefixes()
        self._create_clusters()
        self._create_devices()
        self._create_virtual_machines()
        self._create_interfaces()
        self._create_ip_addresses(no_pool=options["no_ip_pool"])
        self._create_databases()
        self._print_counts()
        self._print_hard_case_summary()
        self.stdout.write(self.style.SUCCESS("Synthetic dataset generation completed."))

    def _scaled_targets(self):
        t = self.cfg["targets"]
        # Keep enough structural objects for all five sites in smoke mode.
        return {
            "switches": scaled(t["switches"], self.scale),
            "hypervisors": scaled(t["hypervisors"], self.scale),
            "virtual_machines": scaled(t["virtual_machines"], self.scale),
            "databases": scaled(t["databases"], self.scale),
            "ip_addresses": scaled(t["ip_addresses"], self.scale),
            "racks": scaled(t["racks"], self.scale, minimum=len(self.cfg["sites"])),
            "clusters": scaled(t["clusters"], self.scale, minimum=len(self.cfg["sites"])),
            "vlans": scaled(t["vlans"], self.scale, minimum=len(self.cfg["sites"])),
        }

    def _assert_clean(self):
        checks = [
            Device.objects.filter(name__startswith="syn-"),
            VirtualMachine.objects.filter(name__startswith="syn-vm-"),
            IPAddress.objects.filter(description__startswith=SYN_MARK),
            Service.objects.filter(description__startswith=f"{SYN_MARK}database"),
        ]
        if any(q.exists() for q in checks):
            raise CommandError("Synthetic data already exists. Re-run with --reset on the test database.")

    def _reset(self):
        self.stdout.write(self.style.WARNING("Deleting existing synthetic rows..."))
        # GenericForeignKey assignments are easiest to clean safely by deleting synthetic IP rows first.
        IPAddress.objects.filter(description__startswith=SYN_MARK).delete()
        Service.objects.filter(description__startswith=f"{SYN_MARK}database").delete()
        VirtualMachine.objects.filter(name__startswith="syn-vm-").delete()
        Device.objects.filter(name__startswith="syn-").delete()
        Cluster.objects.filter(name__startswith="syn-cluster-").delete()
        Prefix.objects.filter(description__startswith=SYN_MARK).delete()
        VLAN.objects.filter(description__startswith=SYN_MARK).delete()
        VRF.objects.filter(name__startswith="SYN-VRF-").delete()
        Rack.objects.filter(name__startswith="SYN-").delete()
        Location.objects.filter(slug__startswith="syn-").delete()
        Site.objects.filter(slug__startswith="syn-").delete()
        # Regions/reference objects are deliberately retained because existing environments may reuse them.
        self.stdout.write(self.style.SUCCESS("Synthetic rows deleted."))

    def _create_geography(self):
        vn, _ = Region.objects.get_or_create(name="SYN Vietnam", parent=None, defaults={"slug": "syn-vietnam"})
        region_names = {
            "north": ("SYN North", "syn-north"),
            "central": ("SYN Central", "syn-central"),
            "south": ("SYN South", "syn-south"),
        }
        self.regions = {}
        for key, (name, slug) in region_names.items():
            obj, _ = Region.objects.get_or_create(name=name, parent=vn, defaults={"slug": slug})
            self.regions[key] = obj

        self.sites = {}
        for item in self.cfg["sites"]:
            # Prefix slug to guarantee reset can identify our sites while preserving readable names.
            slug = f"syn-{item['slug']}"
            site, _ = Site.objects.get_or_create(
                slug=slug,
                defaults={
                    "name": item["name"],
                    "status": "active",
                    "region": self.regions[item["region"]],
                    "facility": f"SYN-{item['code']}",
                    "latitude": Decimal(str(item["latitude"])),
                    "longitude": Decimal(str(item["longitude"])),
                    "time_zone": "Asia/Ho_Chi_Minh",
                    "description": "Synthetic datacenter generated for integration/stress testing",
                },
            )
            self.sites[item["slug"]] = site

        self.locations = defaultdict(list)
        room_count = int(self.cfg.get("rooms_per_site", 4))
        for item in self.cfg["sites"]:
            site = self.sites[item["slug"]]
            for room_idx in range(1, room_count + 1):
                room, _ = Location.objects.get_or_create(
                    site=site,
                    slug=f"syn-{item['slug']}-room-{room_idx:02d}",
                    defaults={
                        "name": f"SYN Room {room_idx:02d}",
                        "description": "Synthetic datacenter room",
                    },
                )
                self.locations[item["slug"]].append(room)

    def _create_reference_data(self):
        self.roles = {}
        for slug, name, vm_role in [
            ("syn-network-switch", "SYN Network Switch", False),
            ("syn-hypervisor", "SYN Hypervisor", False),
            ("syn-virtual-machine", "SYN Virtual Machine", True),
        ]:
            role, _ = DeviceRole.objects.get_or_create(
                slug=slug,
                defaults={"name": name, "color": "9e9e9e", "vm_role": vm_role},
            )
            self.roles[slug] = role

        self.platform_specs = {}
        self.switch_types = {}
        for spec in self.cfg["switch_platforms"]:
            manufacturer, _ = Manufacturer.objects.get_or_create(
                name=spec["manufacturer"], defaults={"slug": spec["manufacturer"].lower().replace(" ", "-")}
            )
            platform, _ = Platform.objects.get_or_create(
                slug=spec["slug"],
                defaults={
                    "name": spec["name"],
                    "manufacturer": manufacturer,
                    "napalm_driver": spec.get("napalm_driver", ""),
                    "description": "Synthetic platform reference",
                },
            )
            dtype, _ = DeviceType.objects.get_or_create(
                manufacturer=manufacturer,
                slug=f"syn-{spec['slug']}-{spec['device_model'].lower().replace(' ', '-')}",
                defaults={
                    "model": f"SYN {spec['device_model']}",
                    "u_height": 1,
                    "is_full_depth": True,
                },
            )
            self.platform_specs[spec["slug"]] = (spec, platform)
            self.switch_types[spec["slug"]] = dtype

        dell, _ = Manufacturer.objects.get_or_create(name="Dell", defaults={"slug": "dell"})
        self.compute_platforms = {}
        compute_catalogs = self.cfg.get("compute_os_catalog", []) + self.cfg.get("vm_os_catalog", [])
        for os_spec in compute_catalogs:
            pslug = os_spec["platform_slug"]
            if pslug not in self.compute_platforms:
                platform, _ = Platform.objects.get_or_create(
                    slug=pslug,
                    defaults={
                        "name": os_spec["name"],
                        "napalm_driver": "",
                        "description": "Synthetic compute operating system",
                    },
                )
                self.compute_platforms[pslug] = platform
        self.hypervisor_type, _ = DeviceType.objects.get_or_create(
            manufacturer=dell,
            slug="syn-poweredge-r650",
            defaults={"model": "SYN PowerEdge R650", "u_height": 1, "is_full_depth": True},
        )

        self.cluster_type, _ = ClusterType.objects.get_or_create(
            slug="syn-vsphere", defaults={"name": "SYN vSphere", "description": "Synthetic virtualization cluster"}
        )
        self.cluster_groups = {}
        for item in self.cfg["sites"]:
            group, _ = ClusterGroup.objects.get_or_create(
                slug=f"syn-{item['slug']}",
                defaults={"name": f"SYN Cluster Group {item['code']}", "description": "Synthetic cluster group"},
            )
            self.cluster_groups[item["slug"]] = group

    def _ensure_custom_fields(self):
        """Create custom fields used to expose software versions and hard-case ground truth."""
        content_types = [
            ContentType.objects.get_for_model(Device),
            ContentType.objects.get_for_model(VirtualMachine),
            ContentType.objects.get_for_model(Service),
        ]
        definitions = [
            ("syn_asset_class", "Synthetic Asset Class", "select", ["switch", "hypervisor", "vm", "database_service"]),
            ("syn_software_name", "Synthetic Software Name", "text", None),
            ("syn_software_version", "Synthetic Software Version", "text", None),
            ("syn_case", "Synthetic Case", "select", ["normal", "legacy", "vulnerable", "legacy_vulnerable", "malformed"]),
            ("syn_eol", "Synthetic EOL", "boolean", None),
            ("syn_known_vulnerable", "Synthetic Known Vulnerable", "boolean", None),
            ("syn_vulnerability_ids", "Synthetic Vulnerability IDs", "json", None),
            (
                "syn_failure_mode",
                "Synthetic Failure Mode",
                "select",
                ["none", "timeout", "auth_failure", "connection_refused", "port_mismatch", "tls_expired", "version_parse_error"],
            ),
        ]
        for name, label, field_type, choices in definitions:
            defaults = {
                "label": label,
                "type": field_type,
                "required": False,
                "description": "Ground truth generated by the synthetic datacenter fixture.",
            }
            if choices is not None:
                defaults["choices"] = choices
            cf, _ = CustomField.objects.get_or_create(name=name, defaults=defaults)
            changed = False
            if cf.label != label:
                cf.label = label
                changed = True
            if cf.type != field_type:
                cf.type = field_type
                changed = True
            if choices is not None and list(cf.choices or []) != choices:
                cf.choices = choices
                changed = True
            if changed:
                cf.save()
            cf.content_types.set(content_types)
        self.stdout.write("Synthetic hard-case custom fields ready.")

    def _site_counts(self, total):
        return apportion(total, self.cfg["sites"])

    def _create_racks(self):
        counts = self._site_counts(self.targets["racks"])
        self.racks = defaultdict(list)
        batch = []
        site_key_for_obj = []
        for site_idx, item in enumerate(self.cfg["sites"]):
            site_key = item["slug"]
            for n in range(1, counts[site_idx] + 1):
                rooms = self.locations[site_key]
                room = rooms[(n - 1) % len(rooms)]
                batch.append(
                    Rack(
                        name=f"SYN-{item['code']}-R{n:04d}",
                        site=self.sites[site_key],
                        location=room,
                        status="active",
                        type="4-post-cabinet",
                        width=19,
                        u_height=42,
                        comments="Synthetic rack",
                    )
                )
                site_key_for_obj.append(site_key)
        Rack.objects.bulk_create(batch, batch_size=1000)
        for obj, site_key in zip(batch, site_key_for_obj):
            self.racks[site_key].append(obj)
        self.stdout.write(f"Racks: {len(batch)}")

    def _create_vrfs_vlans_prefixes(self):
        self.vrfs = {}
        for idx, item in enumerate(self.cfg["sites"], start=1):
            vrf, _ = VRF.objects.get_or_create(
                name=f"SYN-VRF-{item['code']}",
                defaults={
                    "rd": f"65000:{idx}",
                    "enforce_unique": True,
                    "description": f"Synthetic VRF for {item['name']}",
                },
            )
            self.vrfs[item["slug"]] = vrf
            Prefix.objects.get_or_create(
                prefix=self.cfg["ip"]["private_pools"][item["slug"]],
                vrf=vrf,
                defaults={
                    "site": self.sites[item["slug"]],
                    "status": "active",
                    "description": f"{SYN_MARK}private-parent:{item['slug']}",
                },
            )
            Prefix.objects.get_or_create(
                prefix=self.cfg["ip"]["external_sim_pools"][item["slug"]],
                vrf=vrf,
                defaults={
                    "site": self.sites[item["slug"]],
                    "status": "active",
                    "description": f"{SYN_MARK}external-sim-parent:{item['slug']}",
                },
            )

        vlan_counts = self._site_counts(self.targets["vlans"])
        self.vlans = defaultdict(list)
        vlan_objs = []
        vlan_site_keys = []
        for site_idx, item in enumerate(self.cfg["sites"]):
            # Each site has its own VLAN namespace. Stay below VID 4094.
            count = vlan_counts[site_idx]
            if count > 4000:
                raise CommandError("This simple generator supports at most 4000 VLANs/site")
            for n in range(1, count + 1):
                vlan_objs.append(
                    VLAN(
                        site=self.sites[item["slug"]],
                        vid=90 + n,
                        name=f"SYN-{item['code']}-VLAN-{n:04d}",
                        status="active",
                        description=f"{SYN_MARK}vlan:{item['slug']}",
                    )
                )
                vlan_site_keys.append(item["slug"])
        VLAN.objects.bulk_create(vlan_objs, batch_size=1000)
        for obj, site_key in zip(vlan_objs, vlan_site_keys):
            self.vlans[site_key].append(obj)
        self.stdout.write(f"VLANs: {len(vlan_objs)}")

    def _create_clusters(self):
        counts = self._site_counts(self.targets["clusters"])
        self.clusters = defaultdict(list)
        objs = []
        keys = []
        for site_idx, item in enumerate(self.cfg["sites"]):
            for n in range(1, counts[site_idx] + 1):
                objs.append(
                    Cluster(
                        name=f"syn-cluster-{item['code'].lower()}-{n:04d}",
                        type=self.cluster_type,
                        group=self.cluster_groups[item["slug"]],
                        site=self.sites[item["slug"]],
                        comments="Synthetic cluster",
                    )
                )
                keys.append(item["slug"])
        Cluster.objects.bulk_create(objs, batch_size=1000)
        for obj, key in zip(objs, keys):
            self.clusters[key].append(obj)
        self.stdout.write(f"Clusters: {len(objs)}")

    def _create_devices(self):
        self.devices_by_site = defaultdict(list)
        self.switches_by_site = defaultdict(list)
        self.hypervisors_by_site = defaultdict(list)

        # Switches: platform counts are deterministic; version hard cases are guaranteed by weighted plans.
        switch_site_counts = self._site_counts(self.targets["switches"])
        platform_specs = self.cfg["switch_platforms"]
        switch_objs = []
        switch_keys = []
        global_counter = 1
        for site_idx, site_item in enumerate(self.cfg["sites"]):
            site_key = site_item["slug"]
            platform_counts = apportion(switch_site_counts[site_idx], platform_specs)
            local_counter = 1
            for platform_idx, spec in enumerate(platform_specs):
                _, platform = self.platform_specs[spec["slug"]]
                dtype = self.switch_types[spec["slug"]]
                count = platform_counts[platform_idx]
                versions = spec.get("versions", [])
                if not versions:
                    raise CommandError(f"switch platform {spec['slug']} has no versions catalog")
                version_plan = make_weighted_plan(count, versions)
                self.rng.shuffle(version_plan)
                for version_profile in version_plan:
                    racks = self.racks[site_key]
                    rack = racks[(local_counter - 1) % len(racks)]
                    cf = case_data(version_profile, "switch", software_name=spec["name"])
                    switch_objs.append(
                        Device(
                            name=f"syn-sw-{site_item['code'].lower()}-{spec['slug']}-{global_counter:06d}",
                            device_type=dtype,
                            device_role=self.roles["syn-network-switch"],
                            platform=platform,
                            site=self.sites[site_key],
                            location=rack.location,
                            rack=rack,
                            status="active",
                            serial=f"SYNSW{global_counter:010d}",
                            comments=f"Synthetic network switch; case={cf['syn_case']}",
                            custom_field_data=cf,
                        )
                    )
                    switch_keys.append(site_key)
                    global_counter += 1
                    local_counter += 1
        Device.objects.bulk_create(switch_objs, batch_size=2000)
        for obj, key in zip(switch_objs, switch_keys):
            self.devices_by_site[key].append(obj)
            self.switches_by_site[key].append(obj)
        self.stdout.write(f"Switches: {len(switch_objs)}")

        # Physical compute/hypervisors: includes explicit legacy cases such as CentOS 4.
        hv_site_counts = self._site_counts(self.targets["hypervisors"])
        os_catalog = self.cfg.get("compute_os_catalog", [])
        if not os_catalog:
            raise CommandError("compute_os_catalog must not be empty")
        hv_objs = []
        hv_keys = []
        global_counter = 1
        for site_idx, site_item in enumerate(self.cfg["sites"]):
            site_key = site_item["slug"]
            clusters = self.clusters[site_key]
            racks = self.racks[site_key]
            os_plan = make_weighted_plan(hv_site_counts[site_idx], os_catalog)
            self.rng.shuffle(os_plan)
            for n, os_profile in enumerate(os_plan, start=1):
                rack = racks[(n - 1) % len(racks)]
                cf = case_data(os_profile, "hypervisor", software_name=os_profile["name"])
                hv_objs.append(
                    Device(
                        name=f"syn-hv-{site_item['code'].lower()}-{global_counter:06d}",
                        device_type=self.hypervisor_type,
                        device_role=self.roles["syn-hypervisor"],
                        platform=self.compute_platforms[os_profile["platform_slug"]],
                        site=self.sites[site_key],
                        location=rack.location,
                        rack=rack,
                        cluster=clusters[(n - 1) % len(clusters)],
                        status="active",
                        serial=f"SYNHV{global_counter:010d}",
                        comments=f"Synthetic hypervisor; case={cf['syn_case']}",
                        custom_field_data=cf,
                    )
                )
                hv_keys.append(site_key)
                global_counter += 1
        Device.objects.bulk_create(hv_objs, batch_size=2000)
        for obj, key in zip(hv_objs, hv_keys):
            self.devices_by_site[key].append(obj)
            self.hypervisors_by_site[key].append(obj)
        self.stdout.write(f"Hypervisors: {len(hv_objs)}")

    def _create_virtual_machines(self):
        vm_site_counts = self._site_counts(self.targets["virtual_machines"])
        os_catalog = self.cfg.get("vm_os_catalog", [])
        if not os_catalog:
            raise CommandError("vm_os_catalog must not be empty")
        self.vms_by_site = defaultdict(list)
        objs = []
        keys = []
        global_counter = 1
        for site_idx, site_item in enumerate(self.cfg["sites"]):
            site_key = site_item["slug"]
            clusters = self.clusters[site_key]
            os_plan = make_weighted_plan(vm_site_counts[site_idx], os_catalog)
            self.rng.shuffle(os_plan)
            for n, os_profile in enumerate(os_plan, start=1):
                shape = [(2, 4096, 50), (4, 8192, 100), (8, 16384, 200), (16, 32768, 500)][(n - 1) % 4]
                cf = case_data(os_profile, "vm", software_name=os_profile["name"])
                objs.append(
                    VirtualMachine(
                        cluster=clusters[(n - 1) % len(clusters)],
                        platform=self.compute_platforms[os_profile["platform_slug"]],
                        name=f"syn-vm-{site_item['code'].lower()}-{global_counter:07d}",
                        status="active",
                        role=self.roles["syn-virtual-machine"],
                        vcpus=Decimal(shape[0]),
                        memory=shape[1],
                        disk=shape[2],
                        comments=f"Synthetic virtual machine; case={cf['syn_case']}",
                        custom_field_data=cf,
                    )
                )
                keys.append(site_key)
                global_counter += 1
        VirtualMachine.objects.bulk_create(objs, batch_size=2000)
        for obj, key in zip(objs, keys):
            self.vms_by_site[key].append(obj)
        self.stdout.write(f"Virtual machines: {len(objs)}")

    def _create_interfaces(self):
        self.device_interfaces_by_site = defaultdict(list)
        self.vm_interfaces_by_site = defaultdict(list)

        dev_ifaces = []
        dev_keys = []
        for site_item in self.cfg["sites"]:
            key = site_item["slug"]
            vlans = self.vlans[key]
            for idx, dev in enumerate(self.devices_by_site[key]):
                vlan = vlans[idx % len(vlans)] if vlans else None
                dev_ifaces.append(
                    Interface(
                        device=dev,
                        name="mgmt0",
                        type="1000base-t",
                        enabled=True,
                        mgmt_only=True,
                        mode="access" if vlan else "",
                        untagged_vlan=vlan,
                        description="Synthetic management interface",
                    )
                )
                dev_keys.append(key)
        Interface.objects.bulk_create(dev_ifaces, batch_size=5000)
        for obj, key in zip(dev_ifaces, dev_keys):
            self.device_interfaces_by_site[key].append(obj)
        self.stdout.write(f"Device interfaces: {len(dev_ifaces)}")

        vm_ifaces = []
        vm_keys = []
        for site_item in self.cfg["sites"]:
            key = site_item["slug"]
            vlans = self.vlans[key]
            for idx, vm in enumerate(self.vms_by_site[key]):
                vlan = vlans[idx % len(vlans)] if vlans else None
                vm_ifaces.append(
                    VMInterface(
                        virtual_machine=vm,
                        name="eth0",
                        enabled=True,
                        mode="access" if vlan else "",
                        untagged_vlan=vlan,
                        description="Synthetic VM interface",
                    )
                )
                vm_keys.append(key)
        VMInterface.objects.bulk_create(vm_ifaces, batch_size=5000)
        for obj, key in zip(vm_ifaces, vm_keys):
            self.vm_interfaces_by_site[key].append(obj)
        self.stdout.write(f"VM interfaces: {len(vm_ifaces)}")

    def _create_ip_addresses(self, no_pool=False):
        total = self.targets["ip_addresses"]
        private_total = int(round(total * float(self.cfg["ip"]["private_ratio"])))
        external_total = total - private_total
        private_counts = self._site_counts(private_total)
        external_counts = self._site_counts(external_total)
        batch_size = int(self.cfg["ip"].get("batch_size", 5000))

        interface_ct = ContentType.objects.get_for_model(Interface)
        vm_interface_ct = ContentType.objects.get_for_model(VMInterface)

        device_updates = []
        vm_updates = []
        created_total = 0

        for site_idx, site_item in enumerate(self.cfg["sites"]):
            key = site_item["slug"]
            vrf = self.vrfs[key]
            endpoints = []
            for iface, dev in zip(self.device_interfaces_by_site[key], self.devices_by_site[key]):
                endpoints.append((interface_ct, iface.pk, dev, "device"))
            for iface, vm in zip(self.vm_interfaces_by_site[key], self.vms_by_site[key]):
                endpoints.append((vm_interface_ct, iface.pk, vm, "vm"))

            requested_private = private_counts[site_idx]
            if requested_private < len(endpoints):
                raise CommandError(
                    f"Private IP target for {key} ({requested_private}) is smaller than endpoint count ({len(endpoints)}). "
                    "Increase ip_addresses/private_ratio or use a larger --scale."
                )

            addr_iter = host_addresses(self.cfg["ip"]["private_pools"][key], requested_private)
            # Assigned IPs first.
            assigned_pairs = []
            batch = []
            for endpoint in endpoints:
                ct, object_id, parent, parent_kind = endpoint
                ip_obj = IPAddress(
                    address=next(addr_iter),
                    vrf=vrf,
                    status="active",
                    assigned_object_type=ct,
                    assigned_object_id=object_id,
                    description=f"{SYN_MARK}private-assigned:{key}",
                )
                batch.append(ip_obj)
                assigned_pairs.append((ip_obj, parent, parent_kind))
                if len(batch) >= batch_size:
                    IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                    created_total += len(batch)
                    batch.clear()
                    self._progress_ips(created_total, total)
            if batch:
                IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                created_total += len(batch)
                self._progress_ips(created_total, total)

            for ip_obj, parent, parent_kind in assigned_pairs:
                parent.primary_ip4_id = ip_obj.pk
                if parent_kind == "device":
                    device_updates.append(parent)
                else:
                    vm_updates.append(parent)

            # Remaining private pool IPs are unassigned inventory/reserved capacity.
            if not no_pool:
                remaining = requested_private - len(endpoints)
                batch = []
                for _ in range(remaining):
                    batch.append(
                        IPAddress(
                            address=next(addr_iter),
                            vrf=vrf,
                            status="reserved" if (_ % 10 == 0) else "active",
                            description=f"{SYN_MARK}private-pool:{key}",
                        )
                    )
                    if len(batch) >= batch_size:
                        IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                        created_total += len(batch)
                        batch.clear()
                        self._progress_ips(created_total, total)
                if batch:
                    IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                    created_total += len(batch)
                    self._progress_ips(created_total, total)

                # External/Internet-facing simulation addresses. These use CGNAT/shared
                # space intentionally so the generator never injects real public IPv4s.
                ext_iter = host_addresses(self.cfg["ip"]["external_sim_pools"][key], external_counts[site_idx])
                batch = []
                for n in range(external_counts[site_idx]):
                    batch.append(
                        IPAddress(
                            address=next(ext_iter),
                            vrf=vrf,
                            status="active",
                            role="vip" if n % 20 == 0 else "",
                            description=f"{SYN_MARK}internet-sim:{key}",
                        )
                    )
                    if len(batch) >= batch_size:
                        IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                        created_total += len(batch)
                        batch.clear()
                        self._progress_ips(created_total, total)
                if batch:
                    IPAddress.objects.bulk_create(batch, batch_size=batch_size)
                    created_total += len(batch)
                    self._progress_ips(created_total, total)

        if device_updates:
            Device.objects.bulk_update(device_updates, ["primary_ip4"], batch_size=2000)
        if vm_updates:
            VirtualMachine.objects.bulk_update(vm_updates, ["primary_ip4"], batch_size=2000)
        self.stdout.write(f"IP addresses created this run: {created_total}")

    def _progress_ips(self, created, target):
        if created % 100000 < int(self.cfg["ip"].get("batch_size", 5000)):
            self.stdout.write(f"  IP progress: {created:,}/{target:,}")

    def _create_databases(self):
        """Create database services with explicit software-version and runtime-fault cases."""
        total = self.targets["databases"]
        if total == 0:
            return
        all_vms = [vm for site_item in self.cfg["sites"] for vm in self.vms_by_site[site_item["slug"]]]
        if not all_vms:
            raise CommandError("Cannot create database services without virtual machines")

        engine_specs = self.cfg["database_engines"]
        engine_counts = apportion(total, engine_specs)
        failure_specs = self.cfg.get("service_failure_modes", [{"failure_mode": "none", "weight": 1.0}])
        failure_plan = make_weighted_plan(total, failure_specs)
        self.rng.shuffle(failure_plan)
        failure_cursor = 0

        services = []
        global_counter = 1
        vm_cursor = 0
        for engine_idx, spec in enumerate(engine_specs):
            engine_count = engine_counts[engine_idx]
            versions = spec.get("versions", [])
            if not versions:
                raise CommandError(f"database engine {spec['slug']} has no versions catalog")
            version_plan = make_weighted_plan(engine_count, versions)
            self.rng.shuffle(version_plan)
            for version_profile in version_plan:
                vm = all_vms[vm_cursor % len(all_vms)]
                failure = failure_plan[failure_cursor]
                failure_cursor += 1
                cf = case_data(version_profile, "database_service", software_name=spec["name"])
                cf["syn_failure_mode"] = failure["failure_mode"]

                # Keep DB rows valid while introducing semantic/runtime hard cases.
                port = int(spec["port"])
                if cf["syn_failure_mode"] == "port_mismatch":
                    port = port + 1 if port < 65535 else port - 1
                if cf["syn_failure_mode"] == "version_parse_error":
                    cf["syn_software_version"] = f"{cf['syn_software_version']}-UNKNOWN??"

                services.append(
                    Service(
                        virtual_machine=vm,
                        name=f"db-{spec['slug']}-{global_counter:06d}",
                        protocol="tcp",
                        ports=[port],
                        description=f"{SYN_MARK}database:{spec['name']}:case={cf['syn_case']}:fault={cf['syn_failure_mode']}",
                        custom_field_data=cf,
                    )
                )
                vm_cursor += 1
                global_counter += 1
        Service.objects.bulk_create(services, batch_size=2000)
        self.stdout.write(f"Database services: {len(services)}")

    def _print_hard_case_summary(self):
        self.stdout.write("Synthetic hard-case summary:")
        for model, label, base_filter in [
            (Device, "devices", {"name__startswith": "syn-"}),
            (VirtualMachine, "virtual_machines", {"name__startswith": "syn-vm-"}),
            (Service, "database_services", {"description__startswith": f"{SYN_MARK}database"}),
        ]:
            qs = model.objects.filter(**base_filter)
            parts = []
            for case in ["normal", "legacy", "vulnerable", "legacy_vulnerable", "malformed"]:
                count = qs.filter(custom_field_data__syn_case=case).count()
                if count:
                    parts.append(f"{case}={count:,}")
            self.stdout.write(f"  {label:20s} " + (", ".join(parts) if parts else "none"))

        service_qs = Service.objects.filter(description__startswith=f"{SYN_MARK}database")
        faults = []
        for mode in ["timeout", "auth_failure", "connection_refused", "port_mismatch", "tls_expired", "version_parse_error"]:
            count = service_qs.filter(custom_field_data__syn_failure_mode=mode).count()
            if count:
                faults.append(f"{mode}={count:,}")
        self.stdout.write("  service_faults       " + (", ".join(faults) if faults else "none"))

    def _print_counts(self):
        counts = {
            "switches": Device.objects.filter(device_role__slug="syn-network-switch").count(),
            "hypervisors": Device.objects.filter(device_role__slug="syn-hypervisor").count(),
            "virtual_machines": VirtualMachine.objects.filter(name__startswith="syn-vm-").count(),
            "databases_as_services": Service.objects.filter(description__startswith=f"{SYN_MARK}database").count(),
            "ip_addresses": IPAddress.objects.filter(description__startswith=SYN_MARK).count(),
            "racks": Rack.objects.filter(name__startswith="SYN-").count(),
            "clusters": Cluster.objects.filter(name__startswith="syn-cluster-").count(),
            "vlans": VLAN.objects.filter(description__startswith=f"{SYN_MARK}vlan").count(),
        }
        self.stdout.write("Synthetic object counts:")
        for key, value in counts.items():
            self.stdout.write(f"  {key:24s} {value:,}")
